// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID          int32
	WorkspaceID int32
	Name        string
	CreatedAt   pgtype.Timestamp
}

type Session struct {
	ID      int64
	UA      string
	IP      string
	UserID  int32
	Token   string
	Expires pgtype.Timestamp
	Created pgtype.Timestamp
	Updated pgtype.Timestamp
}

type Task struct {
	ID       int32
	BoardID  int32
	Title    string
	Details  pgtype.Text
	Status   pgtype.Text
	Assignee pgtype.Int4
	CreateAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Name      string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Workspace struct {
	ID       int32
	Name     string
	OwnerID  int32
	CreateAt pgtype.Timestamp
}

type WorkspaceMember struct {
	WorkspaceID int32
	UserID      int32
	Role        string
}
